'use strict';
const audio=document.querySelector('#audio'),stage=document.querySelector('#experience'),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),start=document.querySelector('#start'),pause=document.querySelector('#pause'),seek=document.querySelector('#seek'),gentle=document.querySelector('#gentle');
const mappings={
'4_guitar':{h:280,type:'cloud',change:true},ezra_fuzz:{h:43,type:'cloud'},blitz:{h:128,type:'streak'},boom_fx:{h:0,type:'boom',white:true},bright_synth_strings:{h:330,type:'veil'},chord_arp:{h:26,type:'pulse'},drums:{h:9,type:'drum'},ezra_main:{h:248,type:'cloud'},ne_growl:{h:355,type:'pulse'},ne_main:{h:198,type:'dots'},sidechain:{h:185,type:'breath'},synth_hat:{h:104,type:'sparks'},synthetic_bass:{h:49,type:'bass'},bass_drop:{h:29,type:'bass'}};
let data,active=false,frame,last=0,w=0,h=0,fadeTimer,playTimer,session=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;gentle.checked=reduced;
const ready=fetch('analysis.json').then(r=>{if(!r.ok)throw Error('Analysis unavailable');return r.json()}).then(d=>{data=d;d.tracks=d.tracks.filter(t=>mappings[t.name]).map((t,i)=>({...t,...mappings[t.name],seed:i*2.399,energy:0,previous:0,kick:0}));return d});ready.catch(()=>{});
function resize(){w=innerWidth;h=innerHeight;const ratio=Math.min(devicePixelRatio||1,1.5);canvas.width=w*ratio;canvas.height=h*ratio;ctx.setTransform(ratio,0,0,ratio,0,0)}addEventListener('resize',resize);resize();
function field(x,y,r,hue,alpha,white=false,sx=1,sy=1){if(alpha<.001)return;ctx.save();ctx.translate(x,y);ctx.scale(sx,sy);const g=ctx.createRadialGradient(0,0,0,0,0,r);const col=white?'0,0%,95%':`${hue},85%,58%`;g.addColorStop(0,`hsla(${col},${alpha})`);g.addColorStop(.35,`hsla(${col},${alpha*.55})`);g.addColorStop(1,`hsla(${col},0)`);ctx.fillStyle=g;ctx.fillRect(-r,-r,r*2,r*2);ctx.restore()}
function draw(now){if(!active)return;const dt=Math.min((now-last)/1000||.016,.05);last=now;ctx.globalCompositeOperation='source-over';ctx.fillStyle='black';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='screen';const t=audio.currentTime,quiet=gentle.checked,move=quiet?.23:1,idx=t*data.fps;
for(const s of data.tracks){const i=Math.floor(idx),raw=(s.levels[i]||0)*(1-(idx-i))+(s.levels[i+1]||0)*(idx-i);s.energy+=(raw-s.energy)*(1-Math.exp(-dt*(raw>s.energy?19:6)));s.kick=Math.max(s.kick*Math.exp(-dt*5),Math.max(0,raw-s.previous)*2);s.previous=raw;const e=s.energy;if(e<.004)continue;const phase=t*move,x=w*(.5+.34*Math.sin(phase*.19+s.seed)+.09*Math.sin(phase*.51+s.seed*2)),y=h*(.48+.32*Math.cos(phase*.16+s.seed*1.7));let hue=s.change?(t*12+raw*60)%360:s.h;let r=Math.min(w,h)*(.16+e*.22),a=Math.min(.4,e*.3)*(quiet?.6:1);
if(s.type==='dots'||s.type==='sparks'){const count=s.type==='dots'?32:15;for(let j=0;j<count;j++){const v=j*2.399+s.seed;const dx=w*(.5+.46*Math.sin(v+phase*(.06+j*.002))),dy=h*(.5+.44*Math.cos(v*1.31+phase*.09));const life=.35+.65*(.5+.5*Math.sin(t*(s.type==='dots'?1.2:3)+j));field(dx,dy,(s.type==='dots'?9:16)+e*18,hue,a*life*1.5,false)}continue}
if(s.type==='streak'){const sx=w*((t*.12)%1);for(let j=0;j<7;j++)field(sx-j*w*.028,y+Math.sin(t*1.7+j*.5)*h*.045,r*.43,hue,a*(1-j/9)*(quiet?1:.65+.35*Math.sin(t*25)),false,1.8,.25);continue}
if(s.type==='boom'){field(x,y,r*(1+s.kick*.6),hue,Math.min(.28,a*.7+s.kick*.12),true,1.4,.9);continue}
if(s.type==='breath'){field(x,y,r*1.8,hue,a*.19,false,1.6,1.1);continue}
if(s.type==='bass'){field(x,h*(.64+.23*Math.sin(phase*.14+s.seed)),r*1.4,hue,a*.75,false,1.5,.65);continue}
if(s.type==='drum'||s.type==='pulse')r*=1+Math.min(s.kick,.6)*(quiet?.2:1);
for(let j=0;j<3;j++)field(x+Math.sin(phase*.7+s.seed+j*2)*r*.3,y+Math.cos(phase*.6+j+s.seed)*r*.3,r*(.85+j*.12),hue+j*5,a/(1.8+j*.3),false,s.type==='veil'?2.2:1.2,s.type==='veil'?.45:1);
}
ctx.globalCompositeOperation='source-over';seek.value=t;document.querySelector('#time').textContent=`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;frame=requestAnimationFrame(draw)}
async function enter(){const token=++session;clearTimeout(fadeTimer);start.disabled=true;document.querySelector('#status').textContent='Loading music…';try{await ready;if(token!==session)return;seek.max=data.duration;stage.classList.add('open');stage.setAttribute('aria-hidden','false');document.querySelector('#portfolio').inert=true;document.querySelector('#exit').focus();active=true;last=0;frame=requestAnimationFrame(draw);audio.currentTime=0;pause.textContent='Pause';playTimer=setTimeout(async()=>{if(token!==session)return;try{await audio.play();document.querySelector('#status').textContent=''}catch(e){close();document.querySelector('#status').textContent='Playback could not start. Please try Play again.'}},reduced?200:950)}catch(e){document.querySelector('#status').textContent='Could not load the music. Serve this folder through your website or a local web server.'}finally{start.disabled=false}}
function close(){session++;clearTimeout(playTimer);audio.pause();active=false;cancelAnimationFrame(frame);stage.classList.remove('open');document.querySelector('#portfolio').inert=false;start.focus();fadeTimer=setTimeout(()=>{stage.setAttribute('aria-hidden','true');ctx.clearRect(0,0,w,h)},reduced?200:1000)}
async function toggle(){if(audio.paused){try{await audio.play();pause.textContent='Pause'}catch(e){pause.textContent='Retry play'}}else{audio.pause();pause.textContent='Resume'}}
start.addEventListener('click',enter);document.querySelector('#exit').addEventListener('click',close);pause.addEventListener('click',toggle);audio.addEventListener('ended',close);audio.addEventListener('error',()=>{if(active)close();document.querySelector('#status').textContent='Could not load young-turks.mp3.'});seek.addEventListener('input',()=>{audio.currentTime=Number(seek.value);for(const s of data.tracks){s.energy=0;s.previous=0;s.kick=0}});document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape')close();if(e.code==='Space'&&!['INPUT','BUTTON'].includes(e.target.tagName)){e.preventDefault();toggle()}if(e.key==='Tab'){const nodes=[...stage.querySelectorAll('button,input')],first=nodes[0],end=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus()}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus()}}});
